language: ruby

bundler_args: --without debugger

cache: bundler
sudo: false

before_install:
  - gem --version

script: bundle exec rspec spec

rvm:
  - 1.9.3
  - 2.2
  - 2.3.1
  - ruby-head
  
matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    recipients:
      - niklaus.giger@member.fsf.org
