# Copyright (c) 2015 by Niklaus Giger niklaus.giger@member.fsf.org
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http:#www.eclipse.org/legal/epl-v10.html
#
# This is a setup for running tests
# Security is not really a concern!
#
# FROM postgres:9.4
# RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
# ENV LANG de_DE.utf8
version: '2.0'
services:
  mysql_data_tst_upgrade:
    image: busybox
    networks:
      private:

  mysql:
    image: mysql:5.7
    networks:
      private:
    volumes_from:
      - mysql_data_tst_upgrade
    volumes:
      # File in this directory must not be world readable or the mysqld will simply ignore it!
      - ${PWD}/wheezy/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: elexis
      # username/password must be kept in sync with the AUT_RUN.java and
      # postresql/init_elexis_db.sh
      MYSQL_USER: elexis
      MYSQL_PASSWORD: elexisTest
      MYSQL_DATABASE: tst_upgrade

  pg_data_tst_upgrade:
    image: busybox
    networks:
      private:

  postgres:
    image: postgres:9.1
    networks:
      private:
    volumes_from:
      - pg_data_tst_upgrade
#    volumes:
#      - ${PWD}/upgrader/postgres:/docker-entrypoint-initdb.d
    environment:
      # LANG: 'de_CH.UTF-8' postgres docker 9.1 does not have all locales installed!
      PGUSER: elexis
      POSTGRES_DB: tst_upgrade
      POSTGRES_USER: elexis
      POSTGRES_PASSWORD: elexisTest
  runner:
    build: .
    # image: ngiger/jubula_runner:${JUBULA_RUNNER_VERSION}
    networks:
      private:
      public:
    ports:
      # Force an error if HOST_UID is not given!
      - "127.0.0.1::${HOST_UID}"
    working_dir: /home/elexis
    # We want silently kill the docker after an hour
    entrypoint: /app/create_elexis_user.sh
    volumes:
      - /etc/medelexis.yml:/etc/medelexis.yml
      - ${PWD}/wheezy/assets/create_elexis_user.sh:/app/create_elexis_user.sh
      - ${PWD}/wheezy/assets/daemonize:/app/daemonize
      - ${PWD}/wheezy/assets/periodic_screenshots.sh:/app/periodic_screenshots.sh
      - /opt/db_dumps:/opt/db_dumps
      - /opt/downloads:/opt/downloads
      - ${PWD}:/home/elexis
      # File in this directory must not be world readable or the mysqld will simply ignore it!
      - ${PWD}/wheezy/mysql:/etc/mysql/conf.d
      # - /tmp/.X11-unix:/tmp/.X11-unix # für USE_X11
    # devices: # für USE_X11
      # - /dev/snd # für USE_X11
    depends_on:
        - postgres
#         - mysql
    environment:
    # an empty HOST_UID while creating the jenkinstest gives at least a warning
      HOST_UID: "${HOST_UID}" # We want to map the host_uid as our HOST_ID using create_elexis_user
      DOCKER_OPTS: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"
      PGUSER: elexis
      PGHOST: postgres
      POSTGRES_DB: tst_upgrade
      PGPASSWORD: elexisTest
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: elexisTest
      MYSQL_USER: elexis
      MYSQL_PASSWORD: elexisTest
      MYSQL_DATABASE: tst_upgrade
networks:
  public:
  private:
