# Copyright (c) 2015 by Niklaus Giger niklaus.giger@member.fsf.org
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http:#www.eclipse.org/legal/epl-v10.html
#
# This is a setup for running tests
# Security is not really a concern!
#
# FROM postgres:9.4
# RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
# ENV LANG de_DE.utf8
version: '2.0'
services:
  mysql:
    image: mysql:5.7
    networks:
      private:
    volumes:
      # File in this directory must not be world readable or the mysqld will simply ignore it!
      - ${PWD}/wheezy/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: secretRoot
      # username/password must be kept in sync with the AUT_RUN.java and
      # postresql/init_elexis_db.sh
      MYSQL_USER: elexistest
      MYSQL_PASSWORD: elexisTestPassword
      MYSQL_DATABASE: elexistest

  pgdata:
    image: postgres:9.1
    entrypoint: /bin/bash
    networks:
      private:

  postgres:
    image: postgres:9.1
    networks:
      private:
    volumes_from:
      - pgdata
    volumes:
      - ${PWD}/wheezy/postgres:/docker-entrypoint-initdb.d
    environment:
      # LANG: 'de_CH.UTF-8'
      PGUSER: elexistest
      POSTGRES_DB: elexistest
      POSTGRES_PASSWORD: elexisTestPassword

  jenkinstest:
    build: .
    networks:
      private:
      public:
    # Elexis user uid is 1200
    # user: '1200'
    ports:
      - "${agent_port}:${agent_port}"
    working_dir: /home/elexis
    # We want silently kill the docker after an hour
    entrypoint: '/app/create_elexis_user.sh'
    volumes:
      - ${PWD}/results:/home/elexis/results
      - ${PWD}/container_home_m2:/home/elexis/.m2
      - ${PWD}/container_home:/home/elexis
      - ${PWD}/.git:/home/elexis/.git
      # File in this directory must not be world readable or the mysqld will simply ignore it!
      - ${PWD}/wheezy/mysql:/etc/mysql/conf.d
    #   - /tmp/.X11-unix:/tmp/.X11-unix # für USE_X11
    # devices: # für USE_X11
    #   - /dev/snd # für USE_X11
    depends_on:
        - postgres
        - mysql
    environment:
      HOST_UID: # We want to map 1200 as our HOST_ID using create_elexis_user
      DOCKER_OPTS: "-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"
      PGUSER: elexistest
      PGHOST: postgres
      POSTGRES_DB: elexistest
      POSTGRES_PASSWORD: elexisTestPassword
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: secretRoot
      MYSQL_USER: elexistest
      MYSQL_PASSWORD: elexisTestPassword
      MYSQL_DATABASE: elexistest   #  MYSQL_HOST: mysqlTest
networks:
  public:
  private:
